uxtest: main.cc util.cc shaders.cc shapes.cc vertex.cc texture.cc 
	g++ -lfreetype -lSOIL -lglfw -lGLU -lGL -Iinclude -I/usr/include/freetype2 main.cc util.cc shaders.cc shapes.cc vertex.cc texture.cc -o uxtest

clean: 
	rm uxtest
